-- Migration: Bestellungen-Schema erweitern + ShaktiMat-Bestellung einfügen
-- Ausführen im Supabase SQL-Editor (https://supabase.xqtfive.de)

-- 1. Neue Spalten für bestellungen
ALTER TABLE bestellungen ADD COLUMN rechnungsadresse text null;
ALTER TABLE bestellungen ADD COLUMN versandart text null;
ALTER TABLE bestellungen ADD COLUMN versandkosten text null;
ALTER TABLE bestellungen ADD COLUMN rabatt text null;
ALTER TABLE bestellungen ADD COLUMN mwst text null;
ALTER TABLE bestellungen ADD COLUMN zwischensumme text null;

-- 2. Neue Tabelle: bestellpositionen (Bestellpositionen)
CREATE TABLE public.bestellpositionen (
  id bigint generated by default as identity not null,
  bestellnummer text not null,
  bezeichnung text null,
  menge text null,
  einzelpreis text null,
  constraint bestellpositionen_pkey primary key (id)
);

CREATE INDEX idx_bestellpositionen_bestellnummer ON bestellpositionen(bestellnummer);

-- 3. ShaktiMat-Bestellung einfügen
INSERT INTO bestellungen (bestellnummer, datum, status, gesamtwert, zwischensumme, rabatt, versandkosten, mwst, lieferadresse, rechnungsadresse, versandart)
VALUES (
  '619994',
  '22.01.2026',
  'bestätigt',
  '61,24 €',
  '55,25 €',
  '9,74 €',
  '5,99 €',
  '9,78 €',
  'Uwe Will, Nördliche Hauptstraße 21, 61137 Schöneck',
  'Uwe Will, Nördliche Hauptstraße 21, 61137 Schöneck',
  'DPD Paketversand (1-2 Tage)'
);

-- 4. ShaktiMat-Bestellposition einfügen
INSERT INTO bestellpositionen (bestellnummer, bezeichnung, menge, einzelpreis)
VALUES (
  '619994',
  'Shakti Rückengürtel - L',
  '1',
  '64,99 €'
);
